//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net.Security;
using WCF = global::System.ServiceModel;

namespace MyWCF.EasyNorthwind.ServiceContracts
{
	/// <summary>
	/// Service Contract Class - ProductServiceContract
	/// </summary>
	[WCF::ServiceContract(Namespace = "http://EasyNorthwind.Model/2014/ProductService", Name = "ProductServiceContract", SessionMode = WCF::SessionMode.Allowed, ProtectionLevel = ProtectionLevel.None )]
	public partial interface IProductServiceContract 
	{
		[WCF::FaultContract(typeof(MyWCF.EasyNorthwind.FaultContracts.ProductFault))]
		[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://EasyNorthwind.Model/2014/ProductService/ProductServiceContract/GetProduct", ReplyAction = "http://EasyNorthwind.Model/2014/ProductService/ProductServiceContract/GetProduct", ProtectionLevel = ProtectionLevel.None)]
		MyWCF.EasyNorthwind.MessageContracts.GetProductReponse GetProduct(MyWCF.EasyNorthwind.MessageContracts.GetProductRequest request);
		
	}
}

