//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace MyWCF.EasyNorthwind.ServiceImplementation
{	
	/// <summary>
	/// Service Class - ProductService
	/// </summary>
	[WCF::ServiceBehavior(Name = "ProductService", 
		Namespace = "http://EasyNorthwind.Model/2014/ProductService", 
		InstanceContextMode = WCF::InstanceContextMode.PerSession, 
		ConcurrencyMode = WCF::ConcurrencyMode.Single )]
	public abstract class ProductServiceBase : MyWCF.EasyNorthwind.ServiceContracts.IProductServiceContract
	{
		#region ProductServiceContract Members

		public virtual MyWCF.EasyNorthwind.MessageContracts.GetProductReponse GetProduct(MyWCF.EasyNorthwind.MessageContracts.GetProductRequest request)
		{
			return null;
		}

		#endregion		
		
	}
	
	public partial class ProductService : ProductServiceBase
	{
	}
	
}

