//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace MyWCF.EasyNorthwind.FaultContracts
{
	/// <summary>
	/// Data Contract Class - ProductFault
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://EasyNorthwind.Model/2014/ProductService", Name = "ProductFault")]
	public partial class ProductFault 
	{
		private string faultMessage;
		
		[WcfSerialization::DataMember(Name = "FaultMessage", IsRequired = false, Order = 0)]
		public string FaultMessage
		{
		  get { return faultMessage; }
		  set { faultMessage = value; }
		}				
	}
}

