//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace MyWCF.EasyNorthwind.DataContracts
{
	/// <summary>
	/// Data Contract Class - Product
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://EasyNorthwind.Model/2014/ProductService", Name = "Product")]
	public partial class Product 
	{
		private int productID;
		private string productName;
		private string quantityPerUnit;
		private decimal unitPrice;
		private bool discontinued;
		
		[WcfSerialization::DataMember(Name = "ProductID", IsRequired = false, Order = 0)]
		public int ProductID
		{
		  get { return productID; }
		  set { productID = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ProductName", IsRequired = false, Order = 1)]
		public string ProductName
		{
		  get { return productName; }
		  set { productName = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "QuantityPerUnit", IsRequired = false, Order = 2)]
		public string QuantityPerUnit
		{
		  get { return quantityPerUnit; }
		  set { quantityPerUnit = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "UnitPrice", IsRequired = false, Order = 3)]
		public decimal UnitPrice
		{
		  get { return unitPrice; }
		  set { unitPrice = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Discontinued", IsRequired = false, Order = 4)]
		public bool Discontinued
		{
		  get { return discontinued; }
		  set { discontinued = value; }
		}				
	}
}

