
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace MyWCF.EasyNorthwind.MessageContracts
{
	/// <summary>
	/// Service Contract Class - GetProductRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "GetProductRequest", WrapperNamespace = "http://EasyNorthwind.Model/2014/ProductService")] 
	public partial class GetProductRequest
	{
		private int productID;
	 		
		[WCF::MessageBodyMember(Namespace = "http://EasyNorthwind.Model/2014/ProductService", Name = "ProductID")]
		public int ProductID
		{
			get { return productID; }
			set { productID = value; }
		}
	}
}

